---
title: "scrape catcher framing data"
author: "Owen McGrattan"
date: "11/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(dplyr)
library(readr)
```

```{r}
# lets scrape some prospectus data and see what we get
url <- 'https://legacy.baseballprospectus.com/sortable/index.php?cid=2561630'
prospectus <- read_html(url)
```

```{r}
# to see how this works for 2018 data
tab <- prospectus %>%
  html_nodes("table") %>%
  .[[5]] %>%
  html_table()
frame <- as.data.frame(tab)

colnames(frame) = frame[1, ] 
frame = frame[-1, -1]         
```

```{r}
# repeat for 17, 16, 15
urls <- c('https://legacy.baseballprospectus.com/sortable/index.php?cid=2519180', 'https://legacy.baseballprospectus.com/sortable/index.php?cid=2524612', 'https://legacy.baseballprospectus.com/sortable/index.php?cid=2520766')
for (i in 1:3) {
  prospectus_2 <- read_html(urls[i])

  tab_2 <- prospectus_2 %>%
    html_nodes("table") %>%
    .[[5]] %>%
    html_table()
  frame_2 <- as.data.frame(tab_2)

  colnames(frame_2) = frame_2[1, ] 
  frame_2 = frame_2[-1, -1]
  frame = rbind(frame, frame_2)
}
    
```

```{r message=FALSE, warning=FALSE}
# want to match up catcher names with mlbgameday ids
bat_17 <- read_csv("statcast2017_bat.csv")
bat_18 <- read_csv("statcast2018_bat.csv")
```

```{r}
bats <- rbind(bat_17, bat_18)
bats <- unique(bats[c("player_name", "batter")])
# match player names with ids
colnames(frame)[1] <- "player_name"
bats <- bats %>% select(player_name, batter)
frame_2 <- merge(frame, bats, by = "player_name")
```

```{r}
# save framing data
write.csv(frame, "framing.csv")
write.csv(frame_2, "framing_17_18.csv")
```

